INSERT INTO cities VALUES
('Adana',1,null,null),
('Adıyaman',2,null,null),
('Afyonkarahisar',3,null,null),
('Ağrı',4,null,null),
('Amasya',5,null,null),
('Ankara',6,null,null),
('Antalya',7,null,null),
( 'Artvin',8,null,null),
( 'Aydın',9,null,null),
( 'Balıkesir',10,null,null),
( 'Bilecik',11,null,null),
( 'Bingöl',12,null,null),
( 'Bitlis',13,null,null),
( 'Bolu',14,null,null),
( 'Burdur',15,null,null),
( 'Bursa',16,null,null),
( 'Çanakkale',17,null,null),
( 'Çankırı',18,null,null),
( 'Çorum',19,null,null),
( 'Denizli',20,null,null),
( 'Diyarbakır',21,null,null),
( 'Edirne',22,null,null),
( 'Elâzığ',23,null,null),
( 'Erzincan',24,null,null),
( 'Erzurum',25,null,null),
( 'Eskişehir',26,null,null),
( 'Gaziantep',27,null,null),
('Giresun',28,null,null),
( 'Gümüşhane',29,null,null),
( 'Hakkâri',30,null,null),
( 'Hatay',31,null,null),
( 'Isparta',32,null,null),
( 'Mersin',33,null,null),
( 'İstanbul',34,null,null),
( 'İzmir',35,null,null),
( 'Kars',36,null,null),
( 'Kastamonu',37,null,null),
( 'Kayseri',38,null,null),
( 'Kırklareli',39,null,null),
( 'Kırşehir',40,null,null),
( 'Kocaeli',41,null,null),
( 'Konya',42,null,null),
( 'Kütahya',43,null,null),
( 'Malatya',44,null,null),
( 'Manisa',45,null,null),
( 'Kahramanmaraş',46,null,null),
( 'Mardin',47,null,null),
( 'Muğla',48,null,null),
( 'Muş',49,null,null),
( 'Nevşehir',50,null,null),
( 'Niğde',51,null,null),
( 'Ordu',52,null,null),
( 'Rize',53,null,null),
( 'Sakarya',54,null,null),
( 'Samsun',55,null,null),
( 'Siirt',56,null,null),
('Sinop',57,null,null),
( 'Sivas',58,null,null),
( 'Tekirdağ',59,null,null),
( 'Tokat',60,null,null),
( 'Trabzon',61,null,null),
( 'Tunceli',62,null,null),
( 'Şanlıurfa',63,null,null),
( 'Uşak',64,null,null),
( 'Van',65,null,null),
( 'Yozgat',66,null,null),
( 'Zonguldak',67,null,null),
( 'Aksaray',68,null,null),
( 'Bayburt',69,null,null),
( 'Karaman',70,null,null),
( 'Kırıkkale',71,null,null),
( 'Batman',72,null,null),
( 'Şırnak',73,null,null),
( 'Bartın',74,null,null),
( 'Ardahan',75,null,null),
( 'Iğdır',76,null,null),
( 'Yalova',77,null,null),
( 'Karabük',78,null,null),
( 'Kilis',79,null,null),
( 'Osmaniye',80,null,null),
( 'Düzce',81,null,null);